### ISSUE TITLE
automatically verify & test examples

### ISSUE THREAD

**Issue by woeps** [reason-association/reasonml.org#15]
**To ensure a given quality of the examples, the example-code inside the readmes shall be verified and tested automatically.** (freely quoted from reasonml.org)

Let's use this issue to plan and track the process of this task.
___

1. How should the process to publish and test examples look like?
2. Do you know some tools we could use to achieve  this task?

**Comment by woeps** [comment]
A **process** I can think of to contribute to examples and automatically test them is:

- fork the project
- modify some readme (especially some code blocks)
- run tests of the examples locally
- make pull-request for the changes
- CI automatically tests all examples
- probably merge back into project

---

**How to achieve testing the examples?**
We could parse all readmes and extract the codeblocks with the reason annotation into separate files / modules inside an examples directory, which can be picked up by bsb.
I suggest to have one re file per md-file and put every example inside a module named after the md file or even better after the last heading?
Additionally we could introduce some annotation inside the code-block, which should be valid re syntax, to annotate the supposed result of the last call.
e.g:
```reason
let answer = 42;
answer;
//result:42
```
For every annotation we could create a test using jest.

Therefore `npm run test` would:

- extract the examples into separate re files and modules
- try to compile these modules
- run jest for examples, containing a result annotation

If any of the steps fail, the test would fail.

**Comment by MoOx** [comment]
I like the idea. I want to do the same for reason-react-native docs, to ensure test compile _at least_.

(If that can help for extraction, I am using https://github.com/phenomic/markdown-as-json for reason-react-native docs (this is JS but "it works") and that could help to not handle the md parsing atm & focus on finding code block in some json.)

**Comment by ryyppy** [comment]
@woeps Yes! This is something we definitely want in the platform, especially because most of our content will be in markdown format in some sorts and we could verify all core doc examples in one spot, which is great! We invested some time in this already, but I haven't had the time to try things out, so I give some input as well:

**Regarding tools:**
We have been considering combining [OCaml's mdx](https://github.com/realworldocaml/mdx) with BuckleScript to verify codeblocks in all `.md|x` files.

It think this tool closely reflects the process you described? If we could make that work with `bsc`, I could hook up the test script with our CD.

\cc @ulrikstrid who has already been investing A TON of time on automatically verified docs with his [reason-native-web](https://reason-native-web.github.io/) project.

**Comment by ulrikstrid** [comment]
As I see it there are at least 1 issue with `ocaml-mdx` currently, it only extracts ocaml code so you have to manually keep the reason code up to date and make sure you translate it correctly. This could be fixed either upstream in `ocaml-mdx` or with a tool that makes sure the reason and ocaml examples are in sync, I have been thinking about the latter but have not found the time to do it.

**Comment by woeps** [comment]
Since I didn't know of any existing tooling, I was thinking of simply writing a node-aplication using ReasonML and Buckleacript. Using Streams to parse and transform the data should be pretty performant:
I'd get all existing md files as an array from a configurable source-directory and map those to promises of stream-processes, each consisting of somethink like
```js
let mdStream = createReadstream(mdFile);
mdStream.pipe(moduleTransformer).pipe(createWritestream(reFile));
mdStream.pipe(testTransformer).pipe(createWritestream(testFile))
```

The transformer(s) would simply scan the incoming chunks for codeblocks with e.g. none or reason syntax-annotation and put each in it's own module.
If the modules would get named after the last heading (or similar - which could a transformer accomplish), we could get really nice re files out of it.

**Comment by ulrikstrid** [comment]
@woeps if you want help with the native stuff I would gladly help you out. I have the same username on Discord.

My thought was to create a cli tool that takes a path to a file and a flag for either using reason as the source or ocaml and then just parse codeblocks from that language and create output in the other language.
As long as they are in sync mdx will do the rest.

**Comment by woeps** [comment]
@ulrikstrid Indeed I'd like to help, though my "native knowledge" is very limited yet.

I agree, that a CLI tool would fit, but do we need to specify source using a flag. Couldn't we parse this information from the code-blocks and just specify a "default source type" (re/ml) using a flag in case no syntax-type-annotation is present?
I'm also not sure if we need to create output in different languages (at least for the usecase described here)? - In fact if we can compile and execute the codeblocks directly, what would be the output then? Just the exit code?
Since mdx only consumes codeblocks of shell or ocaml, would it be simpler to just temporarily transform all reason-codeblocks to ocaml and feed the resulting md-files directly to mdx? (I guess this could be somehow achieved by calling refmt for every codeblock found in reason?)

**Comment by nikgraf** [comment]
Since our primary goal currently is docs for the Web stack (Belt and later on e.g. React, maybe even the Dom & Js namespace) wouldn't kind of rule out "native"?

**Comment by ulrikstrid** [comment]
My usecase is slightly different than the one here I think, but I have files like [this](https://github.com/reason-native-web/morph/blob/master/docs/markdown/getting-started.md) that includes both Reason and OCaml examples. With the help of docusaurus I can then have [syntax switching](https://reason-native-web.github.io/docs/morph/http-getting-started).
In my build I feed these files to mdx and build a binaries from it.
So in my case I just want to keep them both in sync and the rest would be handled outside of this tool.

If this somewhat aligns then we could probably build something together, but in either case I would be happy to help if @woeps wants to get into native development. 😄

**Comment by ryyppy** [comment]
@woeps @ulrikstrid @nikgraf After thinking about it, let me state a few points on upsides / downsides for JS vs. Native:

**Notes on BuckleScript / JS / Node:**
- JS doesn't require extra CI setup for fast builds, otherwise we need to introduce `esy` and a whole install / compile step, which is insufficient without CI
- It's probably easier for BuckleScript folks to contribute (not a lot of them do native, like @woeps) and it takes time to get them up to speed with native APIs
- We can get something working pretty quick, and since it's Reason code it's also quite type safe

**Notes on Native:**
- After we got up to speed with development (setting up CI, maybe prebuild binaries for quicker feedback loop etc), it's more stable and better integrated in the OCaml ecosystem
- It's easier to integrate with other OCaml libraries and we can access the structure of the examples more easily (since we can use the parser etc)
- I don't have any benchmarks, but I assume it will be more efficient. Question is if the efficiency is actually that important here?
- I have no idea on how long it will take to make all necessary parts compatible

**The good thing is, that the interfaces are well communicated:**
- We read an `md` / `mdx` file, parse for all code fences with language settings, maybe parse some extra meta data to control the execution (e.g. `only-parse`, `use-refmt`,...)
- First step, just try to compile the examples and see if they work (with bucklescript!)
- Second step, run the examples and compare to specific expected output

So if we keep the JS implementation close to the way `mdx` works, it would be easy to switch the implementation as soon as we can guarantee that it doesn't make the project slower (development / CI wise).

@nikgraf @ulrikstrid I totally see native code / tool in this platform as well. I think the better question here is: I now have these two options, our capacities are currently higher in the JS version (since more ppl are capable of committing time into it - Nik and I are also well versed in the Node platform). We would need extra time to set up and communicate all the processes involved to build the native tool. So if we need to commit a lot of extra time just for getting up to speed with native, I'd rather start with the JS version while we are winding up with the native version (like `esy` and `fastpack` did in the beginning). 

Is this a viable option?

**Comment by woeps** [comment]
Maybe we could manage to create at least interfaces we could use both in native and bsb as well, to ease a later migration in compiler targets?

**Comment by woeps** [comment]
I just thought about an Idea I wanted to share:
What do you think of doing the process the other way around? Writing Examples in separate re files and including parts of the source into the mdx files? I guess we could also achieve this automatically?
Therefore we would be able to "develop" the examples like we would normally do and use a tool like jest for tests. Furthermore we could include all examples, but start writing tests step by step to further improve the quality. 

If we stick to a common structure It shouldn't be too hard to migrate to a fully automated workflow later on.

I don't if this would be better, but I think it's an option which should be considered.

**Comment by ulrikstrid** [comment]
You can always just read the actual file as text and insert it somewhere to render it. This might be a good solution @woeps 👍

**Comment by ryyppy** [comment]
\

> What do you think of doing the process the other way around? Writing Examples in separate re files and including parts of the source into the mdx files? I guess we could also achieve this automatically?

Not a fan of this solution... As a contributor it should be easy to just write documentation and have code snippets at the right location. A system which requires the author to learn to write tests in a specific format and then insert placeholders in the prose text seems really counter intuitive to me.

On a sidenote: Did you know that `bsc` now supports a [standalone mode](https://bucklescript.github.io/docs/en/try)? This will be useful to run / compile the snippets.

**Comment by woeps** [comment]
I totally understand your concerns and I'm not favoring one solution over the other.
But we could still automate tests if we would define a module type for examples
E.g.
```ocaml
module type Example = {
type result;
let example: unit => result;
let result: result;
};

 // and use it like
module SimpleArrayExample = {
type result = array(int);
let example = () => [|1|] |> Array.map(i => i+1);
let result = [|2|];
```
Tests could be generated by iterating over all modules and using the concept of first class modules. To verify we would just check the evaluated example function against the result value.
Is there a way to get all defined modules or would we need to store a list of all modulea manually?

One thing I'm not quite sure how to proceed using the techniques described here is the matter of how to efficiently/conveniently link the example source at the right places.

**Comment by ryyppy** [comment]
Super excited to discuss this and I it's good we talk about design here!

IMO the goal of this is not to do verification tests of the Belt Api (this is BS' job to make sure the implementation works). The most important thing for us is that the examples do compile and that the interfaces and their usage are type checking. To be able to verify trivial conditionals would be nice, but is not mandatory imo.

So:
```
[1,2,3]->Belt.List.map((a) => a + 1) == [2,3,4]
// true
```

Should eventually yield `true` for instance, there shouldn't be nothing more to it (and that's exactly what `ocaml-mdx` is doing right now)!

Being able to integrate really really well in prose text is only possible if we don't add a lot of ceremony around it. Every detail we add, such as `module type ...` and every convention we set `let example = () = ....` and every extra file we need to create in a specific directory sets a hurdle for every new contributor.

Also I am afraid that this will grow to a way more complicated system than anticipated. How do you extract the example value from the module? How do you compare the result with the output of the example? Will we need to introduce `jest` just for that feature? Do we need to compile to a specific build folder with all the newly generated modules? How does the insertion logic for the snippets look like?

I would strongly prefer a system which is as simple as it gets, just to get us started.
Like, if the tool starts out with grabbing all the files in `pages/belt_docs`, parsing the markdown, extracting all code-fences tagged with `reason interface,check` (extra meta tags in markdown code fences) or `reason`, concatenate them with semicolons and pipe it through `bsc -e ".."` and look if there's a non-zero output, maybe give a clean report on where the error occurs (mdx file, line), then I am getting **really** excited 😁.

If we are reaching the milestones I had in mind, I am pretty sure that a more complex testing tool will either be obsolete or a maintenance burden rather quickly (e.g. when we want to switch to odoc generated json data, etc.)

**Comment by woeps** [comment]
I created a Sketch to answer some of your questions (@ryyppy ):
https://sketch.sh/s/qHJQfki3OB6yiZUBQP59O1/

Short:

- No Jest or other dependency needed
- we would use `Example.(example()==result)`
- as long as the modules are compiled in the same directory, I think it shouldn't matter where this is exactly
- my best bet to insert snippets would be a custom component (but this is the most unknown part of the described solution)

**Comment by woeps** [comment]
Although there are still some important questions - regarding the concept of having examples and docs in separate files - not answered yet:
I looked into it and I think a rough first proof of concept could be realised very quickly by combining the code in the previosly linked sketch and the mdx plugin rehype-partials (using just a custom handler for the plugin). Using partials, examples could be embedded similar to this: `<!-- href='BeltArray.re:SimpleArrayExample' -->`
 

- [MDX Docs about Plugins](https://mdxjs.com/advanced/plugins)
- [MDX Plugin: Rehype Partials](https://github.com/mrzmmr/rehype-partials)
- [Example of custom handler for Rehype Partials](https://github.com/mrzmmr/rehype-partials/blob/master/examples/custom-handle/lib/handle.js)

**Comment by ulrikstrid** [comment]
@ryyppy @nikgraf I don't think this was supposed to be closed by that PR right?

**Comment by ryyppy** [comment]
Oh, apparently this was closed by the PR!

Short update from my side (bc this happened while I tried to generate an index from the markdown):
I implemented the logic i mentioned in my comment above, since after copy / pasting and editing so many doc files, I still feel like that all the content should reside in one file and should be edited in pure markdown...

The cool thing though, the test script is using the remark AST, so you can basically do whatever you want with the data. We didn't do logic testing (only compilation testing), so there might be room for improvement if it turns out that we really need more verification. You could even compile and then eval the stdout of bsc and check for a specific result... lots of possibilities without the need of separate Reason test files!

So not sure where to go from here... we can now make sure that examples are compiling, so users can copy paste things from the docs into their editor without any errors.

Should we keep this issue open?

**Comment by baransu** [comment]
Not sure where to put it so I'll comment here.

Some examples require example modules like `IntCmp` in all `Belt.Set` or `Belt.MutableSet` docs. We add example what this module is and why it's required but the current testing script fails in such cases. Do you have any idea how it can be improved?

**Comment by nikgraf** [comment]
@baransu I would say even if it makes the example quite long I would add it to all of them. Personally I rather have it very clear what's needed.

**Comment by woeps** [comment]
Great that you found a more "easy-going" solution!

**Comment by ryyppy** [comment]
I will close this for now, since I believe things will change a lot soon when we start to extract the documentation / examples from the source code
