### ISSUE TITLE
RSS feed for blog

### ISSUE THREAD

**Issue by wezm** [reason-association/reasonml.org#174]
It would be great to have an RSS feed for the blog so folks (like me) can discover new posts automatically and read in the comfort of their feed reader if they desire.

**Comment by ryyppy** [comment]
That's a good idea and luckily this is not hard to implement.

Just in case someone else want to tackle this before I'd do it:
- Write a function `BlogApi.createRssFeed`, which utilizes the `BlogApi.getAllPosts` for retrieving the data
  - Inspiration for the RSS serialization: https://gist.github.com/fredrikbergqvist/36704828353ebf5379a5c08c7583fe2d
- Create a page `/pages/rss.re` or (whatever name is the most common)
- Ideally use getStaticProps to render the feed per build (since blog posts are also generated per build, it can't really get out of sync)... not sure if SSG allows setting the content-type to `text/xml`,  i'd assume there is a way to do that

For the maximum size of the feed, I'd suggest the last 10 blog posts (ordered by ascending date), like it is done in the `pages/blog.re` file.

**Comment by ryyppy** [comment]
@wezm just added RSS support. Could you test it with your preferred RSS feed reader and give feedback?

URL: https://reasonml.org/blog/feed.xml

**Comment by wezm** [comment]
Excellent, thank you. I was able to subscribe in [Reeder](https://www.reederapp.com/) and it worked although there is no article body present. 

![image](https://user-images.githubusercontent.com/21787/81121592-70384100-8f72-11ea-9726-bc1bedfb547a.png)

**Comment by ryyppy** [comment]
the article body is the description meta field within our blog system... articles ported from the different Reason projects don't have that set, unless the editor did some extra writing ... that said, some articles should have a description set.

If you could give me an example of a good looking RSS preview from another RSS feed, I could try to extract some content text from the blog content body if there is no description available!

**Comment by wezm** [comment]
Closing as this is now working for me.
