### ISSUE TITLE
Sidebar: distinguish current module from others?

### ISSUE THREAD

**Issue by nikgraf** [reason-association/reasonml.org#81]
<img width="275" alt="Screenshot 2019-10-27 at 21 45 40" src="https://user-images.githubusercontent.com/223045/67641605-56eb7380-f903-11e9-9440-ebd483014c6c.png">

The currently open Module looks exactly like the other menu entries. I noticed this confused beginners who aren't that familiar with Belt.
I believe it would help if both would look a bit different or there would be some kind of visual horizontal rule.

Rust uses this:
<img width="206" alt="Screenshot 2019-10-27 at 21 46 56" src="https://user-images.githubusercontent.com/223045/67641649-d416e880-f903-11e9-8efe-34904e0a8ca3.png">

**Comment by ryyppy** [comment]
In the latest design, the selected module is more obviously distinguished from the rest of the navigation. Originally I wanted to hold off adapting it for now since I wanted to rework the navigation hierarchy  when we display a more general API overview (which contains Belt as a subnavigation point). But maybe it makes sense to implement it already, just to get a quick benefit?

**Comment by ryyppy** [comment]
Will be tackled by #84

**Comment by ryyppy** [comment]
Fixed
